### PR TITLE
Adding 'default' to require statements

### LINKED ISSUE #194: Icons are not rendered correctly
Hi,
I'm trying to install the extension on the last version of jupyterlab (v1.1.1).
As you can see on the screenshot below, icons are not rendered anymore.

image

After investigation, it seems that the upgrade of babel from version 5 to 6 is responsible of this issue. It's certainly updated in the dependency tree of other packages and extensions in the Jupyter environment.

The require function behavior has changed, and the call to the "require" function (here: https://github.com/jupyterlab/jupyterlab-celltags/blob/master/src/components/tag.tsx#L117) now returns an object, and not a string as expected.

From web browser :

image

From the code, this call returns an object :
`src={require('../../static/add_blue.svg')}`

The fix which returns what's expected for a src attribute :
`src={require('../../static/add_blue.svg').default}`

Another solution would be to use this plugin : https://www.npmjs.com/package/babel-plugin-add-module-exports

Regards,
Jérémy

### PR DESCRIPTION
**Pull request by choldgraf**
This adds `default` to image calls which should fix image linking problems.

Fixes #194

### CODE REVIEW

**Comment by telamonian** [comment]
@choldgraf Given that the UI now appears correct, I think this is all the fix that was really needed. I may still make `celltags` into a test case for the new Jlab icon stuff down the road, but this is the right fix for right now.

**Comment by choldgraf** [comment]
perhaps @jasongrout or @blink1073 could advise if this PR will fix things?

**Comment by telamonian** [comment]
@choldgraf I can now tell you with 100% certainty (well, 99% at least) that this PR will fix the immediate problem. I posted a [detailed explanation](https://github.com/jupyterlab/jupyterlab-celltags/issues/194#issuecomment-537963230) over in the original thread in #194. Short version: `.svg` imports were tweaked in the build system of jlab core in `v1.1`, so now you'll need the `.default` property in order to consume `.svg` files the same way as you were before.

I would strongly urge you to pull this ASAP, since otherwise `jupyterlab-celltags` is kind of busted

**Comment by Zsailer** [comment]
Thanks @choldgraf and @telamonian. Merging this now.

**Comment by telamonian** [comment]
Apparently somehow I just got commit rights... ? Well, problem solved, in any case

**Pull request merged**
